---
- name: Playbook for applying configlets to devices in CloudVision
  hosts: cvp1

  vars_files:
    - ../vars/CVP_model.yml

  tasks:
    - name: Debug CVP_DEVICES_MLAG variable
      debug:
        var: CVP_DEVICES_MLAG

    - name: Apply configlets to devices
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_MLAG }}"
        state: present
        apply_mode: loose
